#rarity is a value

#Type abbreviations to save time.
gs = "Great Sword"
ls = "Long Sword"
sns = "Sword and Shield"
bow = "Bow"
db = "Dual Blades"
hh = "Hunting Horn"
sax = "Switch Axe"
ln = "Lance"
gl = "Gunlance"
cb = "Charge Blade"
ig = "Insect Glaive"
lbg = "Light Bowgun"
hbg = "Heavy Bowgun"
ham = "Hammer"

#Trees to save time.
exp = "Expedition"
grath = "G. Rathalos"
ore = "Ore"
jin = "Jin Dahaad"
que = "Quematrice"
par = "Paralysis"
bone = "Bone"
nud = "Nu Udra"
nrs = "Nerscylla"
xwu = "Xu Wu"
dos = "Doshaguma"
gark = "G. Arkveld"
ark = "Arkveld"
gdos = "G. Doshaguma"
ykk = "Yian Kut-Ku"
gful = "G. Fulgur"
gyp = "Gypceros"
rat = "Rathian"
rath = "Rathalos"
gor = "Gore Magala"
tuna = "Speartuna"
wrk = "Workshop"
rey = "Rey Dau"
bal = "Balahara"
chat = "Chatacabra"
aja = "Ajarakan"
lal = "Lala Barina"
blan = "Blangonga"
grav = "Gravios"
rom = "Rompopolo"
gebo = "G. Ebony Tree"
hir = "Hirabami"