#rarity is a value

#Type abbreviations to save time.
gs = "Great Sword"
ls = "Long Sword"
sns = "Sword and Shield"
bow = "Bow"
db = "Dual Blades"
hh = "Hunting Horn"
sax = "Switch Axe"
ln = "Lance"
gl = "Gunlance"
cb = "Charge Blade"
ig = "Insect Glaive"
lbg = "Light Bowgun"
hbg = "Heavy Bowgun"
ham = "Hammer"

#Trees to save time.
aja = "Ajarakan"
ark = "Arkveld"
gark = "G. Arkveld"
bal = "Balahara"
blan = "Blangonga"
bone = "Bone"
chat = "Chatacabra"
cong = "Congalala"
dos = "Doshaguma"
gdos = "G. Doshaguma"
gebo = "G. Ebony Tree"
gful = "G. Fulgur"
hir = "Hirabami"
exp = "Expedition"
gor = "Gore Magala"
grav = "Gravios"
gyp = "Gypceros"
jin = "Jin Dahaad"
lal = "Lala Barina"
ners = "Nerscylla"
nud = "Nu Udra"
ore = "Ore"
par = "Paralysis"
rath = "Rathalos"
grath = "G. Rathalos"
rat = "Rathian"
rey = "Rey Dau"
rom = "Rompopolo"
que = "Quematrice"
tuna = "Speartuna"
uth = "Uth Duna"
ves = "Vespoid"
wrk = "Workshop"
wat = "Water Element"
xwu = "Xu Wu"
ykk = "Yian Kut-Ku"
